- name: "Teardown Azure Virtual Subnet"
  azure_rm_subnet:
    ad_user: "{{ auth_var['user'] | default(omit) }}"
    password: "{{ auth_var['password'] | default(omit) }}"
    client_id: "{{ auth_var['client_id'] | default(omit) }}"
    tenant: "{{ auth_var['tenant'] | default(omit) }}"
    secret: "{{ auth_var['secret'] | default(omit) }}"
    subscription_id: "{{ auth_var['subscription_id'] | default(omit) }}"
    resource_group: "{{ res_def['resource_group'] | default(omit) }}"
    virtual_network_name: "{{res_def['virtual_network_name']|default(omit)}}"
    name: "{{ res_def['subnet_name'] | default(omit) }}"
    state: 'absent'
