---
- name: "Set cred profile"
  set_fact:
    cred_profile: "{{ res_grp['credentials']['profile'] | default('default') }}"
  when: res_grp['credentials'] is defined

- name: "Get creds from auth driver"
  auth_driver:
    filename: "{{ res_grp['credentials']['filename'] }}"
    cred_type: "azure"
    cred_path: "{{ creds_path | default(default_credentials_path) }}"
    driver: "file"
    vault_enc: "{{ vault_encryption }}"
    vault_pass: "{{ vault_pass }}"
  register: auth_var
  when: res_grp['credentials'] is defined
  no_log: "{{ not auth_debug }}"

- name: "Set auth_var"
  set_fact:
    auth_var: "{{ auth_var['output'][cred_profile] | default('') }}"
  when: auth_var is defined
  no_log: "{{ not auth_debug }}"

- name: "Get topology output data from resources file"
  output_parser:
    output_file: "{{ default_resources_path + '/' + topo_data['topology_name'].replace(' ', '_').lower() + '.output' }}"
  register: topo_output
  when: generate_resources

- name: "set topo_output_resources fact"
  set_fact:
    topo_output_resources: "{{ topo_output.output['content'] }}"
  when: generate_resources

- name: "Get topology output data from RunDB"
  rundb:
    conn_str: "{{ rundb_conn }}"
    operation: get
    table: "{{ target }}"
    key: "outputs"
    run_id: "{{ orig_run_id }}"
    db_schema: "{{ rundb_schema }}"
  register: topo_output_rundb
  when: not generate_resources

- name: "convert set topo_output_resources from rundb"
  set_fact:
    topo_output_json: "{{ topo_output_rundb.output | convert_to_json }}"
  when: not generate_resources

- name: "set topo_output_resources fact rundb"
  set_fact:
    topo_output_resources: "{{ topo_output_json[0]['resources'] | default([]) }}"
  when: not generate_resources

- name: "Teardown resource definitions of current group"
  include: teardown_res_defs.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }}
  with_nested:
    - "{{ res_grp['res_defs'] | default(res_grp['resource_definitions']) }}"
    - ["{{ res_grp['resource_group_name']}}"]
  loop_control:
    loop_var: res_item
